### ISSUE TITLE
pure-menu still has the focusring for individual buttons

### ISSUE THREAD

**Issue by ItsAsbreuk** [yahoo/pure#251]
Personally, i realy don't like the focusring.
Fortunately pure removes this for buttons, but it doesn't remove it for menu-buttons.

I would love to see
```css
.pure-menu li a:focus {
    outline: 0;
}
```
just like pure already does with buttons
```css
.pure-button:focus {
    outline: 0;
}
```
