### ISSUE TITLE
Menu Dropdown gets outline in Chrome (Linux)

### ISSUE THREAD

**Issue by MartinSeeler** [yahoo/pure#31]
I just played around with the examples and noticed [in this one](http://purecss.io/menus/#horizontal-menu) the following behaviour in chrome: if I click on "Other" instead of just hovering, the whole `ul.pure-menu-children` is outlined. This is the computed style, copied from Chrome`s Developer tools:

```css
outline-color: rgb(60, 59, 55);
outline-style: auto;
outline-width: 5px;
```

I'm using Chrome 26 under Linux 3.9.2.

The following fix worked for me [at this point](https://github.com/yui/pure/blob/88813998e40bc711fee6df37b75a732495f5db8c/src/menus/css/menus-core.css#L23):

```css
.pure-menu-open > ul {
  left: 0;
  top: 0;
  visibility: visible;
  outline: 0;
}
```
