### ISSUE TITLE
:focus:invalid and :focus:invalid:focus are the same?

### ISSUE THREAD

**Issue by Billy-** [yahoo/pure#398]
Correct me if I'm wrong, these two selector blocks select the same elements?
```CSS
.pure-form input:focus:invalid,
.pure-form textarea:focus:invalid,
.pure-form select:focus:invalid {
    color: #b94a48;
    /* next line is always overridden */
    border-color: #ee5f5b;
}
.pure-form input:focus:invalid:focus,
.pure-form textarea:focus:invalid:focus,
.pure-form select:focus:invalid:focus {
    border-color: #e9322d;
}
```
https://github.com/yahoo/pure/blob/master/src/forms/css/forms.css#L137
