### ISSUE TITLE
Add message / notification styles

### ISSUE THREAD

**Issue by shevabam** [yahoo/pure#476]
Hello,

I think it would be interesting that messages / notifications blocks are in Pure.

I made something like this:

```css
.pure-message {
    margin: 5px auto;
    padding: 10px;
    text-align: center;
    font-size: 14px;
    border-radius: 2px;
}
.pure-message-error {
    color: #BD6060;
    background-color: #ffdfdf;
}
.pure-message-warning {
    color: #CEA176;
    background-color: #ffffdd;
}
.pure-message-success {
    color: #80A75F;
    background-color: #D6E9C6;
}
.pure-message-info {
    color: #5D92BB;
    background-color: #e1f2ff;
}
```

Does that seem relevant?

Thank you for reading me ;)
