### ISSUE TITLE
一个select的small error

### ISSUE THREAD

**Issue by liuww111** [yahoo/pure#502]
我喜欢使用微软雅黑的字体，但是当我使用的时候发现select的字体高度发生了变化。
I like to use Microsoft YaHei font, but when I use the select font height changes
案例(Case):
&lt;select id="stacked-state" style="
    font-family: "Microsoft YaHei";
"&gt;
            &lt;option&gt;分组一&lt;/option&gt;
            &lt;option&gt;分组二&lt;/option&gt;
            &lt;option&gt;分组三&lt;/option&gt;
        &lt;/select&gt;

**Comment by liuww111** [comment]
link：http://purecss.io/forms/，我在网站上面做了在线测试（I did online testing on the website.）

**Comment by liuww111** [comment]
my blog 我的博客（截图了案例）：http://www.cnblogs.com/RainbowInTheSky/p/4567689.html

**Comment by zechau** [comment]
I think this may work:
```css
.pure-form select {
  /* height: 2.25em; */
 padding: .4375em .6em;
  border: 1px solid #ccc;
  background-color: #fff;
}
```
