### ISSUE TITLE
Animating dropdowns with CSS transition. Any easy solutions?

### ISSUE THREAD

**Issue by chaleybgis** [yahoo/pure#506]
I'm having a bit of trouble using CSS transitions on Pure's dropdowns.  Since Pure uses display:none to hide .pure-menu-children it would seem to be untransition-able.  I've tried a few weak attempts at setting height to 0 and dropping down z-index, but nothing really works right.  Anyone have a simple solution to animating Pure's dropdowns?

**Comment by jamesalley** [comment]
You'll have to remove the display: none with an override, and then decide how you want to hide it. For example:

http://jsfiddle.net/james_alley/o96pvv4k/

**Comment by chaleybgis** [comment]
Thanks James.  Here's what I'm doing in case anyone else wants to take a look:

```css
.pure-menu-children {
    display: block;
    visibility:hidden;
    opacity:0;
    transition: opacity 200ms linear;
}
.pure-menu-allow-hover:hover>.pure-menu-children, .pure-menu-active>.pure-menu-children {
    visibility:visible;
    opacity:1;
}
```

I understand this has the implication of hiding sub navigation for screen readers but I was unsatisfied with attempts using a fixed height with dynamic menus.  If anyone has a better solution that is screen reader friendly, please chime in!
