### ISSUE TITLE
Visibility classes .pure-visible-* .pure-hidden-* 

### ISSUE THREAD

**Issue by montalvomiguelo** [yahoo/pure#527]
I'm using **Pure 0.6.0** but the visibility classes have been removed since **Pure 0.5.0**.  Why they have been removed?. I think they are very useful to control which elements we want to see depending on the browsing environment.

In **Pure 0.6.0** What do you do instead ? ... To copy that from **Pure 0.4.2** ?

``` css
@media (min-width: 980px) {
  .pure-visible-phone {
    display: none;
  }
  .pure-visible-tablet {
    display: none;
  }
  .pure-hidden-desktop {
    display: none;
  }
}

@media (max-width: 767px) {
  .pure-hidden-phone {
    display: none;
  }
  .pure-visible-desktop {
    display: none;
  }
}

@media (min-width: 768px) and (max-width: 979px) {
  .pure-hidden-tablet {
    display: none;
  }
  .pure-visible-desktop {
    display: none;
  }
}

```

**Comment by jamesalley** [comment]
If this was a new PR against Pure, I would probably reject it, as these device classes, while a useful way of thinking in 2010, are now not really too useful, as we have tablets and phones of all sizes, and desktops with touch.

Still, you could implement something like this yourself, and think of "phone" as just a "phone-like experience" whether it's experienced on an actual phone, or in a multi-tasking view on an iPad, or in a small window on a desktop.

**Comment by montalvomiguelo** [comment]
What's the way in Pure ... I need to implement the hamburger menu just for small devices (may be extending from bootstrap) and large devices  could see the pure-menu-horizontal ... What's the way in new pure .... Manual media queries for individual modules or maybe the reusable visibility classes from 0.4.2

**Comment by jamesalley** [comment]
Manual media queries for individual modules. Just go ahead and specify your own breakpoints. Pure is intended as a clean starting point, not a feature-rich framework for all things.

**Comment by montalvomiguelo** [comment]
:+1: thx

**Comment by denizdogan** [comment]
Did anything come from this? These are very useful helper classes that don't add much weight.

**Comment by redonkulus** [comment]
@denizdogan outcome would be for this to be handled in userland to keep the breadth of use cases for Pure.css .... pure :)

**Comment by tererero** [comment]
@redonkulus I want to contest the opinion of @redonkulus. A CSS framework should expect no backend to render a static website in a responsive (mobile **and** desktop) mode on every screen size.

**Comment by pieterdd** [comment]
I echo the sentiments expressed in this thread. Sometimes responsive design isn't as simple as letting grid elements take up a bit more or less space. In rare cases, you need to show/hide certain HTML tags on different screen sizes to provide a good user experience.

Every other CSS framework with responsive grid support I've used so far has these visibility classes because they're very useful. Yes, I could definitely implement this manually with additional CSS rules. I'm sympathetic to the argument that you wanna keep Pure CSS free of unnecessary bells and whistles. But the power of a good CSS framework is that it comes with batteries included, so to speak. And I really see this as part of the batteries.

Would you reconsider adding this feature? Or which approach do you suggest for cases where resizing units of the grid layout isn't good enough?

**Comment by lkraav** [comment]
> Would you reconsider adding this feature? Or which approach do you suggest for cases where resizing units of the grid layout isn't good enough?

I'm not sure if a solid pull request contribution ever appeared, showing how to handle the main use cases and also some of the edge cases. That's probably where this issue got stuck.

**Comment by pieterdd** [comment]
Let's see if we can agree on an implementation. I've seen @montalvomiguelo's proposal earlier in this thread, and I might have a middle ground between simplicity and flexibility. How about this?

| CSS class | Meaning | Implementation |
| ---            | ---          | ---                      |
| `pure-hidden-(sm\|md\|lg\|xl)` | Hide element from breakpoint sm/md/lg/xl and up _(and show it otherwise)_ | `display: none` if screen width >= breakpoint |
| `pure-visible-(sm\|md\|lg\|xl)` | Show element from breakpoint sm/md/lg/xl and up _(and hide it otherwise)_ | `display: none` if screen width < breakpoint |

**Comment by lkraav** [comment]
For comparison, this is my current internal implementation.

```scss
$small: only screen and (min-width: 35.5em);  /*  568px */                                                                                                                                                                                                                      
$medium: only screen and (min-width: 48em);   /*  768px */                                                                                                                                                                                                                      
$large: only screen and (min-width: 64em);    /* 1024px */                                                                                                                                                                                                                      
$x-large: only screen and (min-width: 80em);  /* 1280px */                                                                                                                                                                                                                      
$retina: only screen and (min-width: 90em);   /* 1440px */                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                
@media screen and (max-width: 35.438em) { // .pure-hidden-xs                                                                                                                                                                                                                    
    .pure-hidden-xs { display: none !important; }                                                                                                                                                                                                                               
    .pure-visible-sm { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-md { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-lg { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-xl { display: none !important; }                                                                                                                                                                                                                              
}                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                
@media screen and (min-width: 35.5em) and (max-width: 47.938em) { // .pure-hidden-sm                                                                                                                                                                                            
    .pure-visible-xs { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-md { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-lg { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-xl { display: none !important; }                                                                                                                                                                                                                              
    .pure-hidden-sm { display: none !important; }                                                                                                                                                                                                                               
}                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                
@media screen and (min-width: 48em) and (max-width: 63.938em) { // .pure-hidden-md                                                                                                                                                                                              
    .pure-visible-xs { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-sm { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-lg { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-xl { display: none !important; }                                                                                                                                                                                                                              
    .pure-hidden-md { display: none !important; }                                                                                                                                                                                                                               
}                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                
@media screen and (min-width: 64em) and (max-width: 79.938em) { // .pure-hidden-lg                                                                                                                                                                                              
    .pure-visible-xs { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-sm { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-md { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-xl { display: none !important; }                                                                                                                                                                                                                              
    .pure-hidden-lg { display: none !important; }                                                                                                                                                                                                                               
}                                                                                                                                                                                                                                                                               
@media screen and (min-width: 80em) and (max-width: 89.938em) { // .pure-hidden-xl                                                                                                                                                                                              
    .pure-visible-xs { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-sm { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-md { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-lg { display: none !important; }                                                                                                                                                                                                                              
    .pure-hidden-xl { display: none !important; }                                                                                                                                                                                                                               
}                                                                                                                                                                                                                                                                               
@media screen and (min-width: 90em) { // .pure-hidden-ret                                                                                                                                                                                                                       
    .pure-visible-xs { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-sm { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-md { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-lg { display: none !important; }                                                                                                                                                                                                                              
    .pure-visible-xl { display: none !important; }                                                                                                                                                                                                                              
    .pure-hidden-ret { display: none !important; }                                                                                                                                                                                                                              
}
```
