### ISSUE TITLE
DropDown Menus // pure-menu-separator : Vertical separator instead of a horizontal one

### ISSUE THREAD

**Issue by grfrm99** [yahoo/pure#545]
If you add a menu separator in the drop down menu demo (http://purecss.io/menus/ ) than you get a vertical line instead of a horizontal line. See below:
![pure-menu-separator](https://cloud.githubusercontent.com/assets/3863007/12538045/460bedd8-c2cf-11e5-8b74-a8bf03da0701.png)

Tested with "http://yui.yahooapis.com/pure/0.6.0/pure-min.css"

**Comment by redonkulus** [comment]
@grfrm99 what markup are you using to create the separator? Ideally, you should use CSS and not an additional <li> to create the separation. Either way, this might be something specific that the application would do instead of Pure.

**Comment by grfrm99** [comment]
I took the Dropdowns sample in the Pure menu page and added this markup:
  `<li class="pure-menu-separator"></li>` under the "Twitter" menu item

You can see the result here: https://jsfiddle.net/y27ymf8z/

**Comment by redonkulus** [comment]
@grfrm99 thanks for the fiddle, it looks like the separator has to be reset due to the horizontal style setting. Try this out and let me know if that works:

```css
.pure-menu-horizontal .pure-menu-children .pure-menu-separator {
    display: block;
    width: auto;
    height: 1px;
    margin: .3em 0;
}
```
