### ISSUE TITLE
I don't understand the meaning of "*display: inline;"?

### ISSUE THREAD

**Issue by starlightme** [yahoo/pure#553]
Excuse me, I feel quite confused about the css code in [blog layout](http://purecss.io/layouts/blog/)

```css
.nav-item {
    display: inline-block;
    *display: inline;  /*what is *display ?*/
    zoom: 1;
}
```

Could you explain it for me? Thanks a lot!
